=== pebridayanti/webservice/Industri_Jasa/bin/industri_jasa/peb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="pengiriman">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="barang"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="barang">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kode" minOccurs="1"/>
                <xs:element ref="satuan"/>
                <xs:element ref="transaksi"/>
                <xs:element ref="asal"/>
                <xs:element ref="tujuan"/>
                <xs:sequence minOccurs="0">
                    <xs:element ref="pengiriman"/>
                    <xs:element ref="nama"/>
                </xs:sequence>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="kode">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:NCName">
                    <xs:attribute name="motor" type="xs:integer"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="satuan" type="xs:NCName"/>
    <xs:element name="transaksi" type="xs:NCName"/>
    <xs:element name="asal">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pt"/>
                <xs:element ref="kodewilayah"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="tujuan">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="timbangan"/>
                <xs:element ref="pt"/>
                <xs:element ref="kodewilayah"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="timbangan" type="xs:string"/>
    <xs:element name="nama" type="xs:NCName"/>
    <xs:element name="pt" type="xs:string"/>
    <xs:element name="kodewilayah" type="xs:integer"/>
</xs:schema>

=== pebridayanti/webservice/Industri_Jasa/src/industri_jasa/pebrida.xml
<?xml version="1.0" encoding="UTF-8"?>
<pengiriman xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="peb.xsd">
<barang>
<kode motor="001">M1112</kode>
<satuan>kg</satuan>
<transaksi>tunai</transaksi>
<asal>
<pt>JNE</pt>
<kodewilayah>50</kodewilayah>
</asal>
<tujuan>
<pt>POS</pt>
<kodewilayah>549</kodewilayah>
</tujuan>
<pengiriman>barang</pengiriman>
<nama>Pebri</nama>
</barang>
<barang>
<kode>S123</kode>
<satuan>kg</satuan>
<transaksi>tunai</transaksi>
<asal>
<pt>KERETA</pt>
<kodewilayah>78</kodewilayah>
</asal>
<tujuan>
<pt>PUTRA JAYA</pt>
<kodewilayah>120</kodewilayah>
</tujuan>
</barang>
<barang>
<kode>S123</kode>
<satuan>kg</satuan>
<transaksi>tunai</transaksi>
<asal>
<pt>JNE</pt>
<kodewilayah>50</kodewilayah>
</asal>
<tujuan>
<pt>POS</pt>
<kodewilayah>549</kodewilayah>
</tujuan>
</barang>
<barang>
<kode>S123</kode>
<satuan>kg</satuan>
<transaksi>tunai</transaksi>
<asal>
<pt>KERETA</pt>
<kodewilayah>78</kodewilayah>
</asal>
<tujuan>
<pt>PUTRA JAYA</pt>
<kodewilayah>120</kodewilayah>
</tujuan>
</barang>
<barang>
<kode>S123</kode>
<satuan>kg</satuan>
<transaksi>tunai</transaksi>
<asal>
<pt>JNE</pt>
<kodewilayah>50</kodewilayah>
</asal>
<tujuan>
<timbangan>1 kg</timbangan>
<pt>POS</pt>
<kodewilayah>549</kodewilayah>
</tujuan>
</barang>
</pengiriman>
